import type {
  ComponentElement,
  ComponentTemplate,
  InterfacePort,
} from "./types";
import { createId } from "./types";

const port = (
  id: string,
  name: string,
  domain: "power" | "signal",
  edge: "top" | "right" | "bottom" | "left",
  offset: number,
  protocol?: string,
  voltage?: string,
  current?: string,
): InterfacePort => ({ id, name, domain, edge, offset, protocol, voltage, current });

export const componentTemplates: ComponentTemplate[] = [
  {
    id: "dc-dc-24v",
    version: 1,
    name: "宽压 DC-DC 24V",
    description: "18–36V 输入，稳定 24V 母线输出",
    accent: "#e78324",
    width: 220,
    height: 138,
    resources: ["24V POWER BUS"],
    ports: [
      port("wide-in", "18–36V", "power", "left", 0.5, undefined, "18–36V"),
      port("24v-out", "24V", "power", "right", 0.5, undefined, "24V"),
    ],
  },
  {
    id: "stm32-main",
    version: 1,
    name: "STM32 主控板",
    description: "机器人主控制器与现场总线中心",
    accent: "#3a65d8",
    width: 260,
    height: 220,
    resources: ["CAN1", "CAN2", "UART", "RS485", "GPIO"],
    ports: [
      port("24v", "24V", "power", "left", 0.25, undefined, "24V"),
      port("12v-aux", "12V AUX", "power", "left", 0.72, undefined, "12V"),
      port("can1", "CAN 1", "signal", "right", 0.18, "CAN"),
      port("can2", "CAN 2", "signal", "right", 0.34, "CAN"),
      port("uart", "UART", "signal", "right", 0.5, "UART"),
      port("rs485", "RS485", "signal", "right", 0.66, "RS485"),
      port("gpio", "GPIO 3.3V", "signal", "right", 0.82, "GPIO", "3.3V"),
      port("pwm", "PWM", "signal", "bottom", 0.5, "PWM", "3.3V"),
    ],
  },
  {
    id: "dji-center",
    version: 1,
    name: "大疆中心板",
    description: "共享 24V 与 CAN 资源的动力分配中心",
    accent: "#7656cf",
    width: 290,
    height: 300,
    resources: ["24V POWER BUS", "CAN BUS"],
    ports: [
      port("24v-in", "24V IN", "power", "top", 0.5, undefined, "24V"),
      ...Array.from({ length: 6 }, (_, index) =>
        port(
          `can-${index + 1}`,
          `CAN ${index + 1}`,
          "signal",
          "left",
          0.13 + index * 0.145,
          "CAN",
        ),
      ),
      ...Array.from({ length: 6 }, (_, index) =>
        port(
          `24v-${index + 1}`,
          `24V ${index + 1}`,
          "power",
          "right",
          0.13 + index * 0.145,
          undefined,
          "24V",
        ),
      ),
    ],
  },
  {
    id: "esp32-gateway",
    version: 1,
    name: "ESP32 无线网关",
    description: "CAN 与 ESP-NOW 的无线桥接节点",
    accent: "#16847b",
    width: 230,
    height: 170,
    resources: ["CAN", "ESP-NOW"],
    ports: [
      port("24v", "24V", "power", "left", 0.28, undefined, "24V"),
      port("can", "CAN", "signal", "left", 0.72, "CAN"),
      port("esp-now", "ESP-NOW", "signal", "right", 0.5, "ESP-NOW"),
    ],
  },
  {
    id: "npn-photo-gate",
    version: 1,
    name: "NPN 常开光电门",
    description: "24V 供电、NPN 开集电极开关量",
    accent: "#1b8b55",
    width: 225,
    height: 145,
    resources: ["NPN NO"],
    ports: [
      port("24v", "24V", "power", "left", 0.35, undefined, "24V"),
      port("npn", "NPN NO", "signal", "right", 0.55, "NPN", "24V"),
    ],
  },
  {
    id: "opto-24-3v3",
    version: 1,
    name: "光耦隔离板",
    description: "24V 开关量隔离为 3.3V GPIO 逻辑",
    accent: "#0785a5",
    width: 235,
    height: 165,
    resources: ["OPTO ISOLATION"],
    ports: [
      port("24v-in", "24V SIGNAL", "signal", "left", 0.5, "NPN/PNP", "24V"),
      port("3v3-out", "3.3V GPIO", "signal", "right", 0.42, "GPIO", "3.3V"),
      port("3v3-power", "3.3V", "power", "bottom", 0.5, undefined, "3.3V"),
    ],
  },
  {
    id: "bts7960",
    version: 1,
    name: "BTS7960 驱动",
    description: "直流负载 H 桥驱动模块",
    accent: "#c24f43",
    width: 225,
    height: 170,
    resources: ["H-BRIDGE", "PWM"],
    ports: [
      port("24v", "24V", "power", "left", 0.3, undefined, "24V"),
      port("pwm", "PWM", "signal", "left", 0.72, "PWM", "3.3V/5V"),
      port("motor", "MOTOR", "power", "right", 0.5, undefined, "24V"),
    ],
  },
  {
    id: "dji-motor",
    version: 1,
    name: "大疆电机",
    description: "24V 动力与 CAN 控制",
    accent: "#bc5f2f",
    width: 210,
    height: 150,
    resources: ["MOTOR"],
    ports: [
      port("24v", "24V", "power", "left", 0.32, undefined, "24V"),
      port("can", "CAN", "signal", "left", 0.7, "CAN"),
    ],
  },
  {
    id: "servo",
    version: 1,
    name: "舵机",
    description: "独立供电，GPIO 仅提供 PWM 控制信号",
    accent: "#be456f",
    width: 205,
    height: 145,
    resources: ["SERVO"],
    ports: [
      port("power", "5–8.4V", "power", "left", 0.35, undefined, "5–8.4V"),
      port("pwm", "PWM", "signal", "left", 0.7, "PWM", "3.3V"),
    ],
  },
  {
    id: "camera",
    version: 1,
    name: "视觉相机",
    description: "相机设备占位模板，可按实际接口调整",
    accent: "#55677d",
    width: 210,
    height: 150,
    resources: ["VISION"],
    ports: [
      port("power", "12V", "power", "left", 0.35, undefined, "12V"),
      port("data", "ETH/USB", "signal", "left", 0.7, "Ethernet/USB"),
    ],
  },
];

export const templateById = (templateId: string) =>
  componentTemplates.find((template) => template.id === templateId);

export const instantiateTemplate = (
  template: ComponentTemplate,
  x: number,
  y: number,
  overrides: Partial<ComponentElement> = {},
): ComponentElement => ({
  id: createId("component"),
  kind: "component",
  templateId: template.id,
  templateVersion: template.version,
  name: template.name,
  description: template.description,
  accent: template.accent,
  x,
  y,
  width: template.width,
  height: template.height,
  zIndex: 10,
  resources: [...template.resources],
  ports: template.ports.map((item) => ({ ...item })),
  ...overrides,
});
